export const SET_POSTS_BY_USER = "SET_POSTS_BY_USER";
export const SET_POSTS_SKIP_ITEM = "SET_POSTS_SKIP_ITEM";
export const RESET_POSTS_SKIP_ITEM = "RESET_POSTS_SKIP_ITEM";
export const RESET_POSTS_BY_USER = "RESET_POSTS_BY_USER";
export const CANNOT_LOAD_MORE = "CANNOT_LOAD_MORE";